/* ═══════════════════════════════════════════════════════════════════════
   CT/CE TASK BANK — v12.0.2 skeleton (empty — social MCQ fill in progress)
   109 subtopics · 0 tasks
   Generated by scripts/build-v12-skeleton.mjs
   ═══════════════════════════════════════════════════════════════════════ */

window.LEARN_TASKS_CTCE = {
  "v-pres-simple": {
    id: "v-pres-simple",
    name: "Present Simple",
    masterCode: "V-PRES-SIMPLE",
    canonicalSubId: "V-PRES-SIMPLE",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-past-simple": {
    id: "v-past-simple",
    name: "Past Simple",
    masterCode: "V-PAST-SIMPLE",
    canonicalSubId: "V-PAST-SIMPLE",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-fut-simple": {
    id: "v-fut-simple",
    name: "Future Simple",
    masterCode: "V-FUT-SIMPLE",
    canonicalSubId: "V-FUT-SIMPLE",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-pres-cont": {
    id: "v-pres-cont",
    name: "Present Continuous",
    masterCode: "V-PRES-CONT",
    canonicalSubId: "V-PRES-CONT",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-past-cont": {
    id: "v-past-cont",
    name: "Past Continuous",
    masterCode: "V-PAST-CONT",
    canonicalSubId: "V-PAST-CONT",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-pres-perf": {
    id: "v-pres-perf",
    name: "Present Perfect",
    masterCode: "V-PRES-PERF",
    canonicalSubId: "V-PRES-PERF",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-past-perf": {
    id: "v-past-perf",
    name: "Past Perfect",
    masterCode: "V-PAST-PERF",
    canonicalSubId: "V-PAST-PERF",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-pres-perf-cont": {
    id: "v-pres-perf-cont",
    name: "Present Perfect Continuous",
    masterCode: "V-PRES-PERF-CONT",
    canonicalSubId: "V-PRES-PERF-CONT",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-pres-simple-pass": {
    id: "v-pres-simple-pass",
    name: "Present Simple Passive",
    masterCode: "V-PRES-SIMPLE-PASS",
    canonicalSubId: "V-PRES-SIMPLE-PASS",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-past-simple-pass": {
    id: "v-past-simple-pass",
    name: "Past Simple Passive",
    masterCode: "V-PAST-SIMPLE-PASS",
    canonicalSubId: "V-PAST-SIMPLE-PASS",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-fut-simple-pass": {
    id: "v-fut-simple-pass",
    name: "Future Simple Passive",
    masterCode: "V-FUT-SIMPLE-PASS",
    canonicalSubId: "V-FUT-SIMPLE-PASS",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-usedto": {
    id: "v-usedto",
    name: "used to / be used to",
    masterCode: "V-USEDTO",
    canonicalSubId: "V-USEDTO",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-modal": {
    id: "v-modal",
    name: "Modals + equivalents",
    masterCode: "V-MODAL",
    canonicalSubId: "V-MODAL",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-modal-assump": {
    id: "v-modal-assump",
    name: "Modals of assumption [R]",
    masterCode: "V-MODAL-ASSUMP",
    canonicalSubId: "V-MODAL-ASSUMP",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-inf": {
    id: "v-inf",
    name: "Infinitive with/without to [R]",
    masterCode: "V-INF",
    canonicalSubId: "V-INF",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-gerund": {
    id: "v-gerund",
    name: "Gerund [R]",
    masterCode: "V-GERUND",
    canonicalSubId: "V-GERUND",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-subj": {
    id: "v-subj",
    name: "Subjunctive [R]",
    masterCode: "V-SUBJ",
    canonicalSubId: "V-SUBJ",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "v-sot": {
    id: "v-sot",
    name: "Sequence of tenses [R]",
    masterCode: "V-SOT",
    canonicalSubId: "V-SOT",
    canonicalTopicId: "verbs-tenses-voice",
    examPart: "A",
    examBlock: "verb-tenses",
    tasks: []
  },
  "prep-place": {
    id: "prep-place",
    name: "Prepositions of place",
    masterCode: "PREP-PLACE",
    canonicalSubId: "PREP-PLACE",
    canonicalTopicId: "prepositions",
    examPart: "A",
    examBlock: "prepositions-a",
    tasks: []
  },
  "prep-time": {
    id: "prep-time",
    name: "Prepositions of time",
    masterCode: "PREP-TIME",
    canonicalSubId: "PREP-TIME",
    canonicalTopicId: "prepositions",
    examPart: "A",
    examBlock: "prepositions-a",
    tasks: []
  },
  "prep-dir": {
    id: "prep-dir",
    name: "Prepositions of direction",
    masterCode: "PREP-DIR",
    canonicalSubId: "PREP-DIR",
    canonicalTopicId: "prepositions",
    examPart: "A",
    examBlock: "prepositions-a",
    tasks: []
  },
  "prep-dep-verb": {
    id: "prep-dep-verb",
    name: "Dependent prepositions — verb + prep",
    masterCode: "PREP-DEP-VERB",
    canonicalSubId: "PREP-DEP-VERB",
    canonicalTopicId: "prepositions",
    examPart: "A",
    examBlock: "prepositions-a",
    tasks: []
  },
  "prep-dep-adj": {
    id: "prep-dep-adj",
    name: "Dependent prepositions — adjective + prep",
    masterCode: "PREP-DEP-ADJ",
    canonicalSubId: "PREP-DEP-ADJ",
    canonicalTopicId: "prepositions",
    examPart: "A",
    examBlock: "prepositions-a",
    tasks: []
  },
  "prep-dep-noun": {
    id: "prep-dep-noun",
    name: "Dependent prepositions — noun + prep",
    masterCode: "PREP-DEP-NOUN",
    canonicalSubId: "PREP-DEP-NOUN",
    canonicalTopicId: "prepositions",
    examPart: "A",
    examBlock: "prepositions-a",
    tasks: []
  },
  "art-basic": {
    id: "art-basic",
    name: "Definite / indefinite / zero — basic",
    masterCode: "ART-BASIC",
    canonicalSubId: "ART-BASIC",
    canonicalTopicId: "articles",
    examPart: "A",
    examBlock: "articles",
    tasks: []
  },
  "art-geo": {
    id: "art-geo",
    name: "Articles with geo names & streets",
    masterCode: "ART-GEO",
    canonicalSubId: "ART-GEO",
    canonicalTopicId: "articles",
    examPart: "A",
    examBlock: "articles",
    tasks: []
  },
  "art-special": {
    id: "art-special",
    name: "Meals, sports, instruments, proper nouns (non-geo)",
    masterCode: "ART-SPECIAL",
    canonicalSubId: "ART-SPECIAL",
    canonicalTopicId: "articles",
    examPart: "A",
    examBlock: "articles",
    tasks: []
  },
  "art-fixed": {
    id: "art-fixed",
    name: "Fixed phrases with a / the / zero",
    masterCode: "ART-FIXED",
    canonicalSubId: "ART-FIXED",
    canonicalTopicId: "articles",
    examPart: "A",
    examBlock: "articles",
    tasks: []
  },
  "n-count": {
    id: "n-count",
    name: "Countable vs uncountable",
    masterCode: "N-COUNT",
    canonicalSubId: "N-COUNT",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "n-plur": {
    id: "n-plur",
    name: "Plural formation",
    masterCode: "N-PLUR",
    canonicalSubId: "N-PLUR",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "n-poss": {
    id: "n-poss",
    name: "Possessive case",
    masterCode: "N-POSS",
    canonicalSubId: "N-POSS",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-pers": {
    id: "pron-pers",
    name: "Personal + objective",
    masterCode: "PRON-PERS",
    canonicalSubId: "PRON-PERS",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-poss": {
    id: "pron-poss",
    name: "Possessive + absolute",
    masterCode: "PRON-POSS",
    canonicalSubId: "PRON-POSS",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-dem": {
    id: "pron-dem",
    name: "Demonstrative",
    masterCode: "PRON-DEM",
    canonicalSubId: "PRON-DEM",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-refl": {
    id: "pron-refl",
    name: "Reflexive",
    masterCode: "PRON-REFL",
    canonicalSubId: "PRON-REFL",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-indef": {
    id: "pron-indef",
    name: "Indefinite pronouns",
    masterCode: "PRON-INDEF",
    canonicalSubId: "PRON-INDEF",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-int": {
    id: "pron-int",
    name: "Interrogative",
    masterCode: "PRON-INT",
    canonicalSubId: "PRON-INT",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-rel": {
    id: "pron-rel",
    name: "Relative (who/that/which)",
    masterCode: "PRON-REL",
    canonicalSubId: "PRON-REL",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "pron-rel-r": {
    id: "pron-rel-r",
    name: "Relative receptive (what/where/why/when) [R]",
    masterCode: "PRON-REL-R",
    canonicalSubId: "PRON-REL-R",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "adj-comp": {
    id: "adj-comp",
    name: "Degrees of comparison",
    masterCode: "ADJ-COMP",
    canonicalSubId: "ADJ-COMP",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "adj-intens": {
    id: "adj-intens",
    name: "Intensifiers with comparative",
    masterCode: "ADJ-INTENS",
    canonicalSubId: "ADJ-INTENS",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "adj-compound": {
    id: "adj-compound",
    name: "Compound adjectives [R]",
    masterCode: "ADJ-COMPOUND",
    canonicalSubId: "ADJ-COMPOUND",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "num": {
    id: "num",
    name: "Cardinal/ordinal, time & dates",
    masterCode: "NUM",
    canonicalSubId: "NUM",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "adv-comp": {
    id: "adv-comp",
    name: "Adverb degrees of comparison",
    masterCode: "ADV-COMP",
    canonicalSubId: "ADV-COMP",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "adv-special": {
    id: "adv-special",
    name: "too / enough / also",
    masterCode: "ADV-SPECIAL",
    canonicalSubId: "ADV-SPECIAL",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "conj-coord": {
    id: "conj-coord",
    name: "Coordinating conjunctions",
    masterCode: "CONJ-COORD",
    canonicalSubId: "CONJ-COORD",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "conj-subord": {
    id: "conj-subord",
    name: "Subordinating conjunctions",
    masterCode: "CONJ-SUBORD",
    canonicalSubId: "CONJ-SUBORD",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "conj-connect": {
    id: "conj-connect",
    name: "Connective words",
    masterCode: "CONJ-CONNECT",
    canonicalSubId: "CONJ-CONNECT",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-sent-type": {
    id: "syn-sent-type",
    name: "Sentence types",
    masterCode: "SYN-SENT-TYPE",
    canonicalSubId: "SYN-SENT-TYPE",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-question": {
    id: "syn-question",
    name: "Questions (incl. tags)",
    masterCode: "SYN-QUESTION",
    canonicalSubId: "SYN-QUESTION",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-impers": {
    id: "syn-impers",
    name: "Impersonal with formal it",
    masterCode: "SYN-IMPERS",
    canonicalSubId: "SYN-IMPERS",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-goingto": {
    id: "syn-goingto",
    name: "be going to",
    masterCode: "SYN-GOINGTO",
    canonicalSubId: "SYN-GOINGTO",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-there": {
    id: "syn-there",
    name: "There is / There are",
    masterCode: "SYN-THERE",
    canonicalSubId: "SYN-THERE",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-compound": {
    id: "syn-compound",
    name: "Compound sentences",
    masterCode: "SYN-COMPOUND",
    canonicalSubId: "SYN-COMPOUND",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-complex": {
    id: "syn-complex",
    name: "Complex sentences",
    masterCode: "SYN-COMPLEX",
    canonicalSubId: "SYN-COMPLEX",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-wordorder": {
    id: "syn-wordorder",
    name: "Word order",
    masterCode: "SYN-WORDORDER",
    canonicalSubId: "SYN-WORDORDER",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-agree": {
    id: "syn-agree",
    name: "Short agreement (So do I) [R]",
    masterCode: "SYN-AGREE",
    canonicalSubId: "SYN-AGREE",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-cond": {
    id: "syn-cond",
    name: "Conditionals / unreal [R]",
    masterCode: "SYN-COND",
    canonicalSubId: "SYN-COND",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-indirect-q": {
    id: "syn-indirect-q",
    name: "Indirect questions [R]",
    masterCode: "SYN-INDIRECT-Q",
    canonicalSubId: "SYN-INDIRECT-Q",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-complex-subj": {
    id: "syn-complex-subj",
    name: "Complex Subject [R]",
    masterCode: "SYN-COMPLEX-SUBJ",
    canonicalSubId: "SYN-COMPLEX-SUBJ",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-complex-obj": {
    id: "syn-complex-obj",
    name: "Complex Object [R]",
    masterCode: "SYN-COMPLEX-OBJ",
    canonicalSubId: "SYN-COMPLEX-OBJ",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "syn-reported": {
    id: "syn-reported",
    name: "Direct & reported speech [R]",
    masterCode: "SYN-REPORTED",
    canonicalSubId: "SYN-REPORTED",
    canonicalTopicId: "mixed-grammar",
    examPart: "A",
    examBlock: "mixed-grammar",
    tasks: []
  },
  "ei-verb": {
    id: "ei-verb",
    name: "Wrong verb form",
    masterCode: "EI-VERB",
    canonicalSubId: "EI-VERB",
    canonicalTopicId: "error-identification",
    examPart: "A",
    examBlock: "error-id",
    tasks: []
  },
  "ei-prep": {
    id: "ei-prep",
    name: "Wrong preposition",
    masterCode: "EI-PREP",
    canonicalSubId: "EI-PREP",
    canonicalTopicId: "error-identification",
    examPart: "A",
    examBlock: "error-id",
    tasks: []
  },
  "ei-art": {
    id: "ei-art",
    name: "Wrong article",
    masterCode: "EI-ART",
    canonicalSubId: "EI-ART",
    canonicalTopicId: "error-identification",
    examPart: "A",
    examBlock: "error-id",
    tasks: []
  },
  "ei-sva": {
    id: "ei-sva",
    name: "Subject–verb agreement",
    masterCode: "EI-SVA",
    canonicalSubId: "EI-SVA",
    canonicalTopicId: "error-identification",
    examPart: "A",
    examBlock: "error-id",
    tasks: []
  },
  "ei-extra": {
    id: "ei-extra",
    name: "Redundant / wrong extra word",
    masterCode: "EI-EXTRA",
    canonicalSubId: "EI-EXTRA",
    canonicalTopicId: "error-identification",
    examPart: "A",
    examBlock: "error-id",
    tasks: []
  },
  "ei-poss": {
    id: "ei-poss",
    name: "Possessives / each other / else",
    masterCode: "EI-POSS",
    canonicalSubId: "EI-POSS",
    canonicalTopicId: "error-identification",
    examPart: "A",
    examBlock: "error-id",
    tasks: []
  },
  "lex-syn-do-make": {
    id: "lex-syn-do-make",
    name: "do / make",
    masterCode: "LEX-SYN-DO-MAKE",
    canonicalSubId: "LEX-SYN-DO-MAKE",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-say-tell-speak": {
    id: "lex-syn-say-tell-speak",
    name: "tell / say / speak",
    masterCode: "LEX-SYN-SAY-TELL-SPEAK",
    canonicalSubId: "LEX-SYN-SAY-TELL-SPEAK",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-teach-study-learn": {
    id: "lex-syn-teach-study-learn",
    name: "teach / study / learn",
    masterCode: "LEX-SYN-TEACH-STUDY-LEARN",
    canonicalSubId: "LEX-SYN-TEACH-STUDY-LEARN",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-learn-know-findout": {
    id: "lex-syn-learn-know-findout",
    name: "learn / know / find out",
    masterCode: "LEX-SYN-LEARN-KNOW-FINDOUT",
    canonicalSubId: "LEX-SYN-LEARN-KNOW-FINDOUT",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-hear-listen": {
    id: "lex-syn-hear-listen",
    name: "hear / listen",
    masterCode: "LEX-SYN-HEAR-LISTEN",
    canonicalSubId: "LEX-SYN-HEAR-LISTEN",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-lie-lay": {
    id: "lex-syn-lie-lay",
    name: "lie / lay",
    masterCode: "LEX-SYN-LIE-LAY",
    canonicalSubId: "LEX-SYN-LIE-LAY",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-food-meal": {
    id: "lex-syn-food-meal",
    name: "food / meal",
    masterCode: "LEX-SYN-FOOD-MEAL",
    canonicalSubId: "LEX-SYN-FOOD-MEAL",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-borrow-lend": {
    id: "lex-syn-borrow-lend",
    name: "borrow / lend",
    masterCode: "LEX-SYN-BORROW-LEND",
    canonicalSubId: "LEX-SYN-BORROW-LEND",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-look-watch-see": {
    id: "lex-syn-look-watch-see",
    name: "look / watch / see",
    masterCode: "LEX-SYN-LOOK-WATCH-SEE",
    canonicalSubId: "LEX-SYN-LOOK-WATCH-SEE",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-come-go": {
    id: "lex-syn-come-go",
    name: "come / go",
    masterCode: "LEX-SYN-COME-GO",
    canonicalSubId: "LEX-SYN-COME-GO",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-syn-as-like": {
    id: "lex-syn-as-like",
    name: "as / like",
    masterCode: "LEX-SYN-AS-LIKE",
    canonicalSubId: "LEX-SYN-AS-LIKE",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-gram-syn-few-little": {
    id: "lex-gram-syn-few-little",
    name: "few / little",
    masterCode: "LEX-GRAM-SYN-FEW-LITTLE",
    canonicalSubId: "LEX-GRAM-SYN-FEW-LITTLE",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-gram-syn-many-much": {
    id: "lex-gram-syn-many-much",
    name: "many / much",
    masterCode: "LEX-GRAM-SYN-MANY-MUCH",
    canonicalSubId: "LEX-GRAM-SYN-MANY-MUCH",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-gram-syn-other-another": {
    id: "lex-gram-syn-other-another",
    name: "other / another",
    masterCode: "LEX-GRAM-SYN-OTHER-ANOTHER",
    canonicalSubId: "LEX-GRAM-SYN-OTHER-ANOTHER",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-gram-syn-either-neither": {
    id: "lex-gram-syn-either-neither",
    name: "either / neither",
    masterCode: "LEX-GRAM-SYN-EITHER-NEITHER",
    canonicalSubId: "LEX-GRAM-SYN-EITHER-NEITHER",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-adj-adv": {
    id: "lex-adj-adv",
    name: "Adj vs adv confusables",
    masterCode: "LEX-ADJ-ADV",
    canonicalSubId: "LEX-ADJ-ADV",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-part": {
    id: "lex-part",
    name: "Participial adjectives (-ing / -ed)",
    masterCode: "LEX-PART",
    canonicalSubId: "LEX-PART",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "lex-coll": {
    id: "lex-coll",
    name: "Collocations & phrasal verbs",
    masterCode: "LEX-COLL",
    canonicalSubId: "LEX-COLL",
    canonicalTopicId: "lexical-choice",
    examPart: "A",
    examBlock: "vocabulary",
    tasks: []
  },
  "soc-etiquette": {
    id: "soc-etiquette",
    name: "Speech etiquette / dialogue functions",
    masterCode: "SOC-ETIQUETTE",
    canonicalSubId: "SOC-ETIQUETTE",
    canonicalTopicId: "dialogue-sociocultural",
    examPart: "A",
    examBlock: "dialogue",
    tasks: []
  },
  "soc-norms": {
    id: "soc-norms",
    name: "Sociocultural norms / register",
    masterCode: "SOC-NORMS",
    canonicalSubId: "SOC-NORMS",
    canonicalTopicId: "dialogue-sociocultural",
    examPart: "A",
    examBlock: "dialogue",
    tasks: []
  },
  "wf-comp": {
    id: "wf-comp",
    name: "Compound nouns & adjectives",
    masterCode: "WF-COMP",
    canonicalSubId: "WF-COMP",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-n-suf": {
    id: "wf-n-suf",
    name: "Noun suffixes (productive)",
    masterCode: "WF-N-SUF",
    canonicalSubId: "WF-N-SUF",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-adj-suf": {
    id: "wf-adj-suf",
    name: "Adjective suffixes (productive)",
    masterCode: "WF-ADJ-SUF",
    canonicalSubId: "WF-ADJ-SUF",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-num-suf": {
    id: "wf-num-suf",
    name: "Numeral suffixes",
    masterCode: "WF-NUM-SUF",
    canonicalSubId: "WF-NUM-SUF",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-adv-suf": {
    id: "wf-adv-suf",
    name: "Adverb suffix (-ly)",
    masterCode: "WF-ADV-SUF",
    canonicalSubId: "WF-ADV-SUF",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-v-suf": {
    id: "wf-v-suf",
    name: "Verb suffixes",
    masterCode: "WF-V-SUF",
    canonicalSubId: "WF-V-SUF",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-pref": {
    id: "wf-pref",
    name: "Prefixes (productive)",
    masterCode: "WF-PREF",
    canonicalSubId: "WF-PREF",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-n-suf-r": {
    id: "wf-n-suf-r",
    name: "Noun suffixes receptive [R]",
    masterCode: "WF-N-SUF-R",
    canonicalSubId: "WF-N-SUF-R",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-adj-suf-r": {
    id: "wf-adj-suf-r",
    name: "Adjective suffixes receptive [R]",
    masterCode: "WF-ADJ-SUF-R",
    canonicalSubId: "WF-ADJ-SUF-R",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "wf-pref-r": {
    id: "wf-pref-r",
    name: "Prefixes receptive [R]",
    masterCode: "WF-PREF-R",
    canonicalSubId: "WF-PREF-R",
    canonicalTopicId: "word-formation",
    examPart: "B",
    examBlock: "word-formation",
    tasks: []
  },
  "w2s-poly": {
    id: "w2s-poly",
    name: "Polysemous words",
    masterCode: "W2S-POLY",
    canonicalSubId: "W2S-POLY",
    canonicalTopicId: "word-for-two-sentences",
    examPart: "B",
    examBlock: null,
    tasks: []
  },
  "w2s-particle": {
    id: "w2s-particle",
    name: "Particle–noun homonyms",
    masterCode: "W2S-PARTICLE",
    canonicalSubId: "W2S-PARTICLE",
    canonicalTopicId: "word-for-two-sentences",
    examPart: "B",
    examBlock: null,
    tasks: []
  },
  "w2s-action": {
    id: "w2s-action",
    name: "make / take / do / have / get",
    masterCode: "W2S-ACTION",
    canonicalSubId: "W2S-ACTION",
    canonicalTopicId: "word-for-two-sentences",
    examPart: "B",
    examBlock: null,
    tasks: []
  },
  "w2s-body-place": {
    id: "w2s-body-place",
    name: "Body-part / place homonyms",
    masterCode: "W2S-BODY-PLACE",
    canonicalSubId: "W2S-BODY-PLACE",
    canonicalTopicId: "word-for-two-sentences",
    examPart: "B",
    examBlock: null,
    tasks: []
  },
  "w2s-abstract": {
    id: "w2s-abstract",
    name: "Abstract noun homonyms",
    masterCode: "W2S-ABSTRACT",
    canonicalSubId: "W2S-ABSTRACT",
    canonicalTopicId: "word-for-two-sentences",
    examPart: "B",
    examBlock: null,
    tasks: []
  },
  "err-aux": {
    id: "err-aux",
    name: "Redundant auxiliaries",
    masterCode: "ERR-AUX",
    canonicalSubId: "ERR-AUX",
    canonicalTopicId: "error-removal",
    examPart: "B",
    examBlock: "error-removal",
    tasks: []
  },
  "err-prep": {
    id: "err-prep",
    name: "Redundant prepositions",
    masterCode: "ERR-PREP",
    canonicalSubId: "ERR-PREP",
    canonicalTopicId: "error-removal",
    examPart: "B",
    examBlock: "error-removal",
    tasks: []
  },
  "err-art": {
    id: "err-art",
    name: "Redundant articles",
    masterCode: "ERR-ART",
    canonicalSubId: "ERR-ART",
    canonicalTopicId: "error-removal",
    examPart: "B",
    examBlock: "error-removal",
    tasks: []
  },
  "err-pron": {
    id: "err-pron",
    name: "Redundant pronouns",
    masterCode: "ERR-PRON",
    canonicalSubId: "ERR-PRON",
    canonicalTopicId: "error-removal",
    examPart: "B",
    examBlock: "error-removal",
    tasks: []
  },
  "err-int": {
    id: "err-int",
    name: "Redundant intensifiers",
    masterCode: "ERR-INT",
    canonicalSubId: "ERR-INT",
    canonicalTopicId: "error-removal",
    examPart: "B",
    examBlock: "error-removal",
    tasks: []
  },
  "err-para": {
    id: "err-para",
    name: "Parallel-structure errors",
    masterCode: "ERR-PARA",
    canonicalSubId: "ERR-PARA",
    canonicalTopicId: "error-removal",
    examPart: "B",
    examBlock: "error-removal",
    tasks: []
  }
};
