/* ═══════════════════════════════════════════════════════════════════════
 * v12 Learn taxonomy — CT/CE exam order + legacy B1/B2/C1 (v10 banks)
 * Generated by scripts/build-v12-skeleton.mjs — do not hand-edit.
 * ═══════════════════════════════════════════════════════════════════════ */
(function(){
  'use strict';

  var CONFIG = {
    version: 'v12.0.2',
    levels: [
      { id: 'ctce', name: 'CT/CE',  displayShort: 'CT/CE' },
      { id: 'b1',   name: 'B1',     displayShort: 'B1'    },
      { id: 'b2',   name: 'B2',     displayShort: 'B2'    },
      { id: 'c1',   name: 'C1',     displayShort: 'C1'    }
    ],
    flavors: [
      { id: 'social',        name: 'Social Situations'    },
      { id: 'personalities', name: 'Famous Personalities' },
      { id: 'history',       name: 'Historical Facts'     },
      { id: 'science',       name: 'Science & Discovery'  },
      { id: 'quotes',        name: 'Quotes'               }
    ],
    topics: [
      { id: 'verbs-tenses-voice', name: "Verb tenses & voice", examPart: "A", examBlock: "verb-tenses", legacyV10: false, subtopics: [
        { id: 'V-PRES-SIMPLE', name: "Present Simple", levels: { ctce: "v-pres-simple", b1: null, b2: null, c1: null } },
        { id: 'V-PAST-SIMPLE', name: "Past Simple", levels: { ctce: "v-past-simple", b1: null, b2: null, c1: null } },
        { id: 'V-FUT-SIMPLE', name: "Future Simple", levels: { ctce: "v-fut-simple", b1: null, b2: null, c1: null } },
        { id: 'V-PRES-CONT', name: "Present Continuous", levels: { ctce: "v-pres-cont", b1: null, b2: null, c1: null } },
        { id: 'V-PAST-CONT', name: "Past Continuous", levels: { ctce: "v-past-cont", b1: null, b2: null, c1: null } },
        { id: 'V-PRES-PERF', name: "Present Perfect", levels: { ctce: "v-pres-perf", b1: null, b2: null, c1: null } },
        { id: 'V-PAST-PERF', name: "Past Perfect", levels: { ctce: "v-past-perf", b1: null, b2: null, c1: null } },
        { id: 'V-PRES-PERF-CONT', name: "Present Perfect Continuous", levels: { ctce: "v-pres-perf-cont", b1: null, b2: null, c1: null } },
        { id: 'V-PRES-SIMPLE-PASS', name: "Present Simple Passive", levels: { ctce: "v-pres-simple-pass", b1: null, b2: null, c1: null } },
        { id: 'V-PAST-SIMPLE-PASS', name: "Past Simple Passive", levels: { ctce: "v-past-simple-pass", b1: null, b2: null, c1: null } },
        { id: 'V-FUT-SIMPLE-PASS', name: "Future Simple Passive", levels: { ctce: "v-fut-simple-pass", b1: null, b2: null, c1: null } },
        { id: 'V-USEDTO', name: "used to / be used to", levels: { ctce: "v-usedto", b1: null, b2: null, c1: null } },
        { id: 'V-MODAL', name: "Modals + equivalents", levels: { ctce: "v-modal", b1: null, b2: null, c1: null } },
        { id: 'V-MODAL-ASSUMP', name: "Modals of assumption [R]", levels: { ctce: "v-modal-assump", b1: null, b2: null, c1: null } },
        { id: 'V-INF', name: "Infinitive with/without to [R]", levels: { ctce: "v-inf", b1: null, b2: null, c1: null } },
        { id: 'V-GERUND', name: "Gerund [R]", levels: { ctce: "v-gerund", b1: null, b2: null, c1: null } },
        { id: 'V-SUBJ', name: "Subjunctive [R]", levels: { ctce: "v-subj", b1: null, b2: null, c1: null } },
        { id: 'V-SOT', name: "Sequence of tenses [R]", levels: { ctce: "v-sot", b1: null, b2: null, c1: null } },
      ]},
      { id: 'prepositions', name: "Prepositions", examPart: "A", examBlock: "prepositions-a", legacyV10: false, subtopics: [
        { id: 'PREP-PLACE', name: "Prepositions of place", levels: { ctce: "prep-place", b1: null, b2: null, c1: null } },
        { id: 'PREP-TIME', name: "Prepositions of time", levels: { ctce: "prep-time", b1: null, b2: null, c1: null } },
        { id: 'PREP-DIR', name: "Prepositions of direction", levels: { ctce: "prep-dir", b1: null, b2: null, c1: null } },
        { id: 'PREP-DEP-VERB', name: "Dependent prepositions — verb + prep", levels: { ctce: "prep-dep-verb", b1: null, b2: null, c1: null } },
        { id: 'PREP-DEP-ADJ', name: "Dependent prepositions — adjective + prep", levels: { ctce: "prep-dep-adj", b1: null, b2: null, c1: null } },
        { id: 'PREP-DEP-NOUN', name: "Dependent prepositions — noun + prep", levels: { ctce: "prep-dep-noun", b1: null, b2: null, c1: null } },
      ]},
      { id: 'articles', name: "Articles", examPart: "A", examBlock: "articles", legacyV10: false, subtopics: [
        { id: 'ART-BASIC', name: "Definite / indefinite / zero — basic", levels: { ctce: "art-basic", b1: null, b2: null, c1: null } },
        { id: 'ART-GEO', name: "Articles with geo names & streets", levels: { ctce: "art-geo", b1: null, b2: null, c1: null } },
        { id: 'ART-SPECIAL', name: "Meals, sports, instruments, proper nouns (non-geo)", levels: { ctce: "art-special", b1: null, b2: null, c1: null } },
        { id: 'ART-FIXED', name: "Fixed phrases with a / the / zero", levels: { ctce: "art-fixed", b1: null, b2: null, c1: null } },
      ]},
      { id: 'mixed-grammar', name: "Mixed grammar", examPart: "A", examBlock: "mixed-grammar", legacyV10: false, subtopics: [
        { id: 'N-COUNT', name: "Countable vs uncountable", levels: { ctce: "n-count", b1: null, b2: null, c1: null } },
        { id: 'N-PLUR', name: "Plural formation", levels: { ctce: "n-plur", b1: null, b2: null, c1: null } },
        { id: 'N-POSS', name: "Possessive case", levels: { ctce: "n-poss", b1: null, b2: null, c1: null } },
        { id: 'PRON-PERS', name: "Personal + objective", levels: { ctce: "pron-pers", b1: null, b2: null, c1: null } },
        { id: 'PRON-POSS', name: "Possessive + absolute", levels: { ctce: "pron-poss", b1: null, b2: null, c1: null } },
        { id: 'PRON-DEM', name: "Demonstrative", levels: { ctce: "pron-dem", b1: null, b2: null, c1: null } },
        { id: 'PRON-REFL', name: "Reflexive", levels: { ctce: "pron-refl", b1: null, b2: null, c1: null } },
        { id: 'PRON-INDEF', name: "Indefinite pronouns", levels: { ctce: "pron-indef", b1: null, b2: null, c1: null } },
        { id: 'PRON-INT', name: "Interrogative", levels: { ctce: "pron-int", b1: null, b2: null, c1: null } },
        { id: 'PRON-REL', name: "Relative (who/that/which)", levels: { ctce: "pron-rel", b1: null, b2: null, c1: null } },
        { id: 'PRON-REL-R', name: "Relative receptive (what/where/why/when) [R]", levels: { ctce: "pron-rel-r", b1: null, b2: null, c1: null } },
        { id: 'ADJ-COMP', name: "Degrees of comparison", levels: { ctce: "adj-comp", b1: null, b2: null, c1: null } },
        { id: 'ADJ-INTENS', name: "Intensifiers with comparative", levels: { ctce: "adj-intens", b1: null, b2: null, c1: null } },
        { id: 'ADJ-COMPOUND', name: "Compound adjectives [R]", levels: { ctce: "adj-compound", b1: null, b2: null, c1: null } },
        { id: 'NUM', name: "Cardinal/ordinal, time & dates", levels: { ctce: "num", b1: null, b2: null, c1: null } },
        { id: 'ADV-COMP', name: "Adverb degrees of comparison", levels: { ctce: "adv-comp", b1: null, b2: null, c1: null } },
        { id: 'ADV-SPECIAL', name: "too / enough / also", levels: { ctce: "adv-special", b1: null, b2: null, c1: null } },
        { id: 'CONJ-COORD', name: "Coordinating conjunctions", levels: { ctce: "conj-coord", b1: null, b2: null, c1: null } },
        { id: 'CONJ-SUBORD', name: "Subordinating conjunctions", levels: { ctce: "conj-subord", b1: null, b2: null, c1: null } },
        { id: 'CONJ-CONNECT', name: "Connective words", levels: { ctce: "conj-connect", b1: null, b2: null, c1: null } },
        { id: 'SYN-SENT-TYPE', name: "Sentence types", levels: { ctce: "syn-sent-type", b1: null, b2: null, c1: null } },
        { id: 'SYN-QUESTION', name: "Questions (incl. tags)", levels: { ctce: "syn-question", b1: null, b2: null, c1: null } },
        { id: 'SYN-IMPERS', name: "Impersonal with formal it", levels: { ctce: "syn-impers", b1: null, b2: null, c1: null } },
        { id: 'SYN-GOINGTO', name: "be going to", levels: { ctce: "syn-goingto", b1: null, b2: null, c1: null } },
        { id: 'SYN-THERE', name: "There is / There are", levels: { ctce: "syn-there", b1: null, b2: null, c1: null } },
        { id: 'SYN-COMPOUND', name: "Compound sentences", levels: { ctce: "syn-compound", b1: null, b2: null, c1: null } },
        { id: 'SYN-COMPLEX', name: "Complex sentences", levels: { ctce: "syn-complex", b1: null, b2: null, c1: null } },
        { id: 'SYN-WORDORDER', name: "Word order", levels: { ctce: "syn-wordorder", b1: null, b2: null, c1: null } },
        { id: 'SYN-AGREE', name: "Short agreement (So do I) [R]", levels: { ctce: "syn-agree", b1: null, b2: null, c1: null } },
        { id: 'SYN-COND', name: "Conditionals / unreal [R]", levels: { ctce: "syn-cond", b1: null, b2: null, c1: null } },
        { id: 'SYN-INDIRECT-Q', name: "Indirect questions [R]", levels: { ctce: "syn-indirect-q", b1: null, b2: null, c1: null } },
        { id: 'SYN-COMPLEX-SUBJ', name: "Complex Subject [R]", levels: { ctce: "syn-complex-subj", b1: null, b2: null, c1: null } },
        { id: 'SYN-COMPLEX-OBJ', name: "Complex Object [R]", levels: { ctce: "syn-complex-obj", b1: null, b2: null, c1: null } },
        { id: 'SYN-REPORTED', name: "Direct & reported speech [R]", levels: { ctce: "syn-reported", b1: null, b2: null, c1: null } },
      ]},
      { id: 'error-identification', name: "Error identification", examPart: "A", examBlock: "error-id", legacyV10: false, subtopics: [
        { id: 'EI-VERB', name: "Wrong verb form", levels: { ctce: "ei-verb", b1: null, b2: null, c1: null } },
        { id: 'EI-PREP', name: "Wrong preposition", levels: { ctce: "ei-prep", b1: null, b2: null, c1: null } },
        { id: 'EI-ART', name: "Wrong article", levels: { ctce: "ei-art", b1: null, b2: null, c1: null } },
        { id: 'EI-SVA', name: "Subject–verb agreement", levels: { ctce: "ei-sva", b1: null, b2: null, c1: null } },
        { id: 'EI-EXTRA', name: "Redundant / wrong extra word", levels: { ctce: "ei-extra", b1: null, b2: null, c1: null } },
        { id: 'EI-POSS', name: "Possessives / each other / else", levels: { ctce: "ei-poss", b1: null, b2: null, c1: null } },
      ]},
      { id: 'lexical-choice', name: "Lexical choice & vocabulary", examPart: "A", examBlock: "vocabulary", legacyV10: false, subtopics: [
        { id: 'LEX-SYN-DO-MAKE', name: "do / make", levels: { ctce: "lex-syn-do-make", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-SAY-TELL-SPEAK', name: "tell / say / speak", levels: { ctce: "lex-syn-say-tell-speak", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-TEACH-STUDY-LEARN', name: "teach / study / learn", levels: { ctce: "lex-syn-teach-study-learn", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-LEARN-KNOW-FINDOUT', name: "learn / know / find out", levels: { ctce: "lex-syn-learn-know-findout", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-HEAR-LISTEN', name: "hear / listen", levels: { ctce: "lex-syn-hear-listen", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-LIE-LAY', name: "lie / lay", levels: { ctce: "lex-syn-lie-lay", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-FOOD-MEAL', name: "food / meal", levels: { ctce: "lex-syn-food-meal", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-BORROW-LEND', name: "borrow / lend", levels: { ctce: "lex-syn-borrow-lend", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-LOOK-WATCH-SEE', name: "look / watch / see", levels: { ctce: "lex-syn-look-watch-see", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-COME-GO', name: "come / go", levels: { ctce: "lex-syn-come-go", b1: null, b2: null, c1: null } },
        { id: 'LEX-SYN-AS-LIKE', name: "as / like", levels: { ctce: "lex-syn-as-like", b1: null, b2: null, c1: null } },
        { id: 'LEX-GRAM-SYN-FEW-LITTLE', name: "few / little", levels: { ctce: "lex-gram-syn-few-little", b1: null, b2: null, c1: null } },
        { id: 'LEX-GRAM-SYN-MANY-MUCH', name: "many / much", levels: { ctce: "lex-gram-syn-many-much", b1: null, b2: null, c1: null } },
        { id: 'LEX-GRAM-SYN-OTHER-ANOTHER', name: "other / another", levels: { ctce: "lex-gram-syn-other-another", b1: null, b2: null, c1: null } },
        { id: 'LEX-GRAM-SYN-EITHER-NEITHER', name: "either / neither", levels: { ctce: "lex-gram-syn-either-neither", b1: null, b2: null, c1: null } },
        { id: 'LEX-ADJ-ADV', name: "Adj vs adv confusables", levels: { ctce: "lex-adj-adv", b1: null, b2: null, c1: null } },
        { id: 'LEX-PART', name: "Participial adjectives (-ing / -ed)", levels: { ctce: "lex-part", b1: null, b2: null, c1: null } },
        { id: 'LEX-COLL', name: "Collocations & phrasal verbs", levels: { ctce: "lex-coll", b1: null, b2: null, c1: null } },
      ]},
      { id: 'dialogue-sociocultural', name: "Dialogue & sociocultural", examPart: "A", examBlock: "dialogue", legacyV10: false, subtopics: [
        { id: 'SOC-ETIQUETTE', name: "Speech etiquette / dialogue functions", levels: { ctce: "soc-etiquette", b1: null, b2: null, c1: null } },
        { id: 'SOC-NORMS', name: "Sociocultural norms / register", levels: { ctce: "soc-norms", b1: null, b2: null, c1: null } },
      ]},
      { id: 'word-formation', name: "Word formation", examPart: "B", examBlock: "word-formation", legacyV10: false, subtopics: [
        { id: 'WF-COMP', name: "Compound nouns & adjectives", levels: { ctce: "wf-comp", b1: null, b2: null, c1: null } },
        { id: 'WF-N-SUF', name: "Noun suffixes (productive)", levels: { ctce: "wf-n-suf", b1: null, b2: null, c1: null } },
        { id: 'WF-ADJ-SUF', name: "Adjective suffixes (productive)", levels: { ctce: "wf-adj-suf", b1: null, b2: null, c1: null } },
        { id: 'WF-NUM-SUF', name: "Numeral suffixes", levels: { ctce: "wf-num-suf", b1: null, b2: null, c1: null } },
        { id: 'WF-ADV-SUF', name: "Adverb suffix (-ly)", levels: { ctce: "wf-adv-suf", b1: null, b2: null, c1: null } },
        { id: 'WF-V-SUF', name: "Verb suffixes", levels: { ctce: "wf-v-suf", b1: null, b2: null, c1: null } },
        { id: 'WF-PREF', name: "Prefixes (productive)", levels: { ctce: "wf-pref", b1: null, b2: null, c1: null } },
        { id: 'WF-N-SUF-R', name: "Noun suffixes receptive [R]", levels: { ctce: "wf-n-suf-r", b1: null, b2: null, c1: null } },
        { id: 'WF-ADJ-SUF-R', name: "Adjective suffixes receptive [R]", levels: { ctce: "wf-adj-suf-r", b1: null, b2: null, c1: null } },
        { id: 'WF-PREF-R', name: "Prefixes receptive [R]", levels: { ctce: "wf-pref-r", b1: null, b2: null, c1: null } },
      ]},
      { id: 'word-for-two-sentences', name: "Word for two sentences", examPart: "B", examBlock: null, legacyV10: false, subtopics: [
        { id: 'W2S-POLY', name: "Polysemous words", levels: { ctce: "w2s-poly", b1: null, b2: null, c1: null } },
        { id: 'W2S-PARTICLE', name: "Particle–noun homonyms", levels: { ctce: "w2s-particle", b1: null, b2: null, c1: null } },
        { id: 'W2S-ACTION', name: "make / take / do / have / get", levels: { ctce: "w2s-action", b1: null, b2: null, c1: null } },
        { id: 'W2S-BODY-PLACE', name: "Body-part / place homonyms", levels: { ctce: "w2s-body-place", b1: null, b2: null, c1: null } },
        { id: 'W2S-ABSTRACT', name: "Abstract noun homonyms", levels: { ctce: "w2s-abstract", b1: null, b2: null, c1: null } },
      ]},
      { id: 'error-removal', name: "Error removal", examPart: "B", examBlock: "error-removal", legacyV10: false, subtopics: [
        { id: 'ERR-AUX', name: "Redundant auxiliaries", levels: { ctce: "err-aux", b1: null, b2: null, c1: null } },
        { id: 'ERR-PREP', name: "Redundant prepositions", levels: { ctce: "err-prep", b1: null, b2: null, c1: null } },
        { id: 'ERR-ART', name: "Redundant articles", levels: { ctce: "err-art", b1: null, b2: null, c1: null } },
        { id: 'ERR-PRON', name: "Redundant pronouns", levels: { ctce: "err-pron", b1: null, b2: null, c1: null } },
        { id: 'ERR-INT', name: "Redundant intensifiers", levels: { ctce: "err-int", b1: null, b2: null, c1: null } },
        { id: 'ERR-PARA', name: "Parallel-structure errors", levels: { ctce: "err-para", b1: null, b2: null, c1: null } },
      ]},
      { id: 'verb-tenses-legacy', name: "Verb Tenses (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-prs-s', name: "Present Simple", levels: { ctce: null, b1: "b1-prs-s", b2: null, c1: null } },
        { id: 'cs-prs-c', name: "Present Continuous", levels: { ctce: null, b1: "b1-prs-c", b2: null, c1: null } },
        { id: 'cs-pst-s', name: "Past Simple", levels: { ctce: null, b1: "b1-pst-s", b2: null, c1: null } },
        { id: 'cs-pst-c', name: "Past Continuous", levels: { ctce: null, b1: "b1-pst-c", b2: null, c1: null } },
        { id: 'cs-pp-s', name: "Present Perfect Simple", levels: { ctce: null, b1: "b1-pp-s", b2: null, c1: null } },
        { id: 'cs-pp-c', name: "Present Perfect Continuous", levels: { ctce: null, b1: null, b2: "b2-pp-cont", c1: null } },
        { id: 'cs-pst-perf-s', name: "Past Perfect Simple", levels: { ctce: null, b1: null, b2: "b2-pst-perf-s", c1: null } },
        { id: 'cs-pst-perf-c', name: "Past Perfect Continuous", levels: { ctce: null, b1: null, b2: "b2-pst-perf-c", c1: null } },
        { id: 'cs-fut-will', name: "Future with will", levels: { ctce: null, b1: "b1-fut-will", b2: null, c1: null } },
        { id: 'cs-fut-going', name: "Future with going to", levels: { ctce: null, b1: "b1-fut-going", b2: null, c1: null } },
        { id: 'cs-fut-perf', name: "Future Perfect", levels: { ctce: null, b1: null, b2: "b2-fut-perf", c1: null } },
        { id: 'cs-fut-cont', name: "Future Continuous", levels: { ctce: null, b1: null, b2: "b2-fut-cont", c1: null } },
        { id: 'cs-narrative-mix', name: "Narrative tenses (mixed)", levels: { ctce: null, b1: null, b2: "b2-mix-narrative", c1: null } },
      ]},
      { id: 'passive-legacy', name: "Passive (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-pass-mix', name: "Passive — mixed tenses", levels: { ctce: null, b1: "b1-pass-basic", b2: null, c1: null } },
        { id: 'cs-pass-mod', name: "Passive with modals", levels: { ctce: null, b1: null, b2: "b2-pass-mod", c1: null } },
        { id: 'cs-pass-perf', name: "Perfect passive", levels: { ctce: null, b1: null, b2: "b2-pass-perf", c1: null } },
        { id: 'cs-pass-reporting', name: "Reporting-verb passive", levels: { ctce: null, b1: null, b2: "b2-pass-reporting", c1: null } },
        { id: 'cs-pass-have-done', name: "Causative passive (have sth done)", levels: { ctce: null, b1: null, b2: null, c1: "c1-pass-have-done" } },
        { id: 'cs-pass-rep-verb', name: "Advanced reporting passive", levels: { ctce: null, b1: null, b2: null, c1: "c1-pass-rep-verb" } },
      ]},
      { id: 'modals-legacy', name: "Modals (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-mod-can', name: "can / could", levels: { ctce: null, b1: "b1-mod-can", b2: null, c1: null } },
        { id: 'cs-mod-must', name: "must / have to", levels: { ctce: null, b1: "b1-mod-must", b2: null, c1: null } },
        { id: 'cs-mod-should', name: "should / ought to", levels: { ctce: null, b1: "b1-mod-should", b2: null, c1: null } },
        { id: 'cs-mod-pos', name: "Modals — possibility / deduction", levels: { ctce: null, b1: null, b2: "b2-mod-deduct", c1: null } },
        { id: 'cs-mod-past', name: "Modals — past forms", levels: { ctce: null, b1: null, b2: "b2-mod-past", c1: null } },
        { id: 'cs-mod-perfect', name: "Modal perfect", levels: { ctce: null, b1: null, b2: "b2-mod-perfect", c1: null } },
        { id: 'cs-mod-shades', name: "Modals — nuance & shades", levels: { ctce: null, b1: null, b2: null, c1: "c1-mod-shades" } },
        { id: 'cs-mod-historical', name: "Historical / archaic modals", levels: { ctce: null, b1: null, b2: null, c1: "c1-mod-historical" } },
      ]},
      { id: 'conditionals-legacy', name: "Conditionals (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-cond-0', name: "Zero conditional", levels: { ctce: null, b1: "b1-cond-0", b2: null, c1: null } },
        { id: 'cs-cond-1', name: "First conditional", levels: { ctce: null, b1: "b1-cond-1", b2: null, c1: null } },
        { id: 'cs-cond-2', name: "Second conditional", levels: { ctce: null, b1: null, b2: "b2-cond-2", c1: null } },
        { id: 'cs-cond-3', name: "Third conditional", levels: { ctce: null, b1: null, b2: "b2-cond-3", c1: null } },
        { id: 'cs-cond-mixed', name: "Mixed conditionals", levels: { ctce: null, b1: null, b2: "b2-cond-mixed", c1: null } },
        { id: 'cs-cond-implied', name: "Implied conditionals", levels: { ctce: null, b1: null, b2: null, c1: "c1-cond-implied" } },
        { id: 'cs-cond-without-if', name: "Conditionals without if", levels: { ctce: null, b1: null, b2: null, c1: "c1-cond-without-if" } },
      ]},
      { id: 'gerund-infinitive-legacy', name: "Gerund / Infinitive (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-ger-basic', name: "Gerund — basic", levels: { ctce: null, b1: "b1-ger-basic", b2: null, c1: null } },
        { id: 'cs-inf-basic', name: "Infinitive — basic", levels: { ctce: null, b1: "b1-inf-basic", b2: null, c1: null } },
        { id: 'cs-ger-inf-meaning', name: "Verbs that change meaning", levels: { ctce: null, b1: null, b2: "b2-ger-inf-meaning", c1: null } },
      ]},
      { id: 'subordinate-clauses-legacy', name: "Subordinate Clauses (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-sub-general', name: "Subordinate clauses — general", levels: { ctce: null, b1: "b1-sub-gen", b2: "b2-sub-gen", c1: "c1-sub-gen" } },
        { id: 'cs-rel-basic', name: "Relative clauses — basic", levels: { ctce: null, b1: "b1-rel-basic", b2: null, c1: null } },
        { id: 'cs-rel-def', name: "Defining relative clauses", levels: { ctce: null, b1: null, b2: "b2-rel-def", c1: null } },
        { id: 'cs-rel-nondef', name: "Non-defining relative clauses", levels: { ctce: null, b1: null, b2: "b2-rel-nondef", c1: null } },
        { id: 'cs-rel-adv', name: "Relative clauses — advanced", levels: { ctce: null, b1: null, b2: null, c1: "c1-rel-adv" } },
      ]},
      { id: 'comparatives-legacy', name: "Comparatives & Superlatives (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-comp', name: "Comparatives", levels: { ctce: null, b1: "b1-comp-basic", b2: null, c1: null } },
        { id: 'cs-sup', name: "Superlatives", levels: { ctce: null, b1: "b1-sup-basic", b2: null, c1: null } },
      ]},
      { id: 'quantifiers-legacy', name: "Quantifiers (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-quant-some-any', name: "some / any", levels: { ctce: null, b1: "b1-quant-some-any", b2: null, c1: null } },
        { id: 'cs-quant-much-many', name: "much / many", levels: { ctce: null, b1: "b1-quant-much-many", b2: null, c1: null } },
      ]},
      { id: 'articles-legacy', name: "Articles (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-art-indef', name: "Indefinite a/an", levels: { ctce: null, b1: "b1-art-indef", b2: null, c1: null } },
        { id: 'cs-art-def', name: "Definite the", levels: { ctce: null, b1: "b1-art-def", b2: null, c1: null } },
        { id: 'cs-art-abstract', name: "Articles with abstract nouns", levels: { ctce: null, b1: null, b2: "b2-art-abstract", c1: null } },
        { id: 'cs-art-unique', name: "Articles with unique referents", levels: { ctce: null, b1: null, b2: "b2-art-unique", c1: null } },
      ]},
      { id: 'prepositions-legacy', name: "Prepositions & Particles (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-prep-time', name: "Time prepositions", levels: { ctce: null, b1: "b1-prep-time", b2: null, c1: null } },
        { id: 'cs-prep-place', name: "Place prepositions", levels: { ctce: null, b1: "b1-prep-place", b2: null, c1: null } },
        { id: 'cs-prep-verb', name: "Verb + preposition", levels: { ctce: null, b1: "b1-prep-verb-basic", b2: null, c1: null } },
      ]},
      { id: 'word-formation-legacy', name: "Word Formation (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-wf-neg', name: "Negative prefixes", levels: { ctce: null, b1: null, b2: "b2-wf-prefix", c1: null } },
        { id: 'cs-wf-mixed', name: "Mixed word formation", levels: { ctce: null, b1: null, b2: "b2-wf-suffix-adv", c1: null } },
      ]},
      { id: 'vocab-context-legacy', name: "Vocabulary in Context (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-voc-coll', name: "Collocation selection", levels: { ctce: null, b1: null, b2: null, c1: "c1-collocation-adv" } },
        { id: 'cs-voc-reg', name: "Register selection", levels: { ctce: null, b1: null, b2: null, c1: "c1-register-formal" } },
      ]},
      { id: 'question-forms-legacy', name: "Question Forms (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-qtags', name: "Question tags", levels: { ctce: null, b1: "b1-qtags", b2: null, c1: null } },
        { id: 'cs-qwords', name: "Question words", levels: { ctce: null, b1: "b1-qwords", b2: null, c1: null } },
      ]},
      { id: 'reported-speech-legacy', name: "Reported Speech (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-rep-stmt', name: "Reported statements", levels: { ctce: null, b1: null, b2: "b2-rep-stmt", c1: null } },
        { id: 'cs-rep-ques', name: "Reported questions", levels: { ctce: null, b1: null, b2: "b2-rep-ques", c1: null } },
        { id: 'cs-rep-cmd', name: "Reported commands", levels: { ctce: null, b1: null, b2: "b2-rep-cmd", c1: null } },
      ]},
      { id: 'phrasal-verbs-legacy', name: "Phrasal Verbs (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-pv-sep', name: "Separable phrasal verbs", levels: { ctce: null, b1: null, b2: "b2-pv-sep", c1: null } },
        { id: 'cs-pv-insep', name: "Inseparable phrasal verbs", levels: { ctce: null, b1: null, b2: "b2-pv-insep", c1: null } },
        { id: 'cs-pv-3word', name: "Three-word phrasal verbs", levels: { ctce: null, b1: null, b2: "b2-pv-3word", c1: null } },
      ]},
      { id: 'inversion-cleft-legacy', name: "Inversion & Cleft (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-inv-neg', name: "Negative inversion", levels: { ctce: null, b1: null, b2: "b2-inv-basic", c1: "c1-inv-neg" } },
        { id: 'cs-inv-cond', name: "Conditional inversion", levels: { ctce: null, b1: null, b2: null, c1: "c1-inv-cond" } },
        { id: 'cs-cleft-it', name: "It-cleft", levels: { ctce: null, b1: null, b2: null, c1: "c1-cleft-it" } },
        { id: 'cs-cleft-what', name: "What-cleft", levels: { ctce: null, b1: null, b2: null, c1: "c1-cleft-what" } },
      ]},
      { id: 'subjunctive-unreal-legacy', name: "Subjunctive & Unreal (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-subj-basic', name: "Subjunctive — basic", levels: { ctce: null, b1: null, b2: null, c1: "c1-subj-basic" } },
        { id: 'cs-subj-wish', name: "Wish & if only", levels: { ctce: null, b1: null, b2: null, c1: "c1-subj-wish" } },
      ]},
      { id: 'participle-clauses-legacy', name: "Participle Clauses (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-part-clause-pres', name: "Present participle clauses", levels: { ctce: null, b1: null, b2: "b2-part-clause-basic", c1: "c1-part-clause-pres" } },
        { id: 'cs-part-clause-perf', name: "Perfect participle clauses", levels: { ctce: null, b1: null, b2: null, c1: "c1-part-clause-perf" } },
      ]},
      { id: 'discourse-cohesion-legacy', name: "Discourse & Cohesion (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-disc-markers', name: "Discourse markers", levels: { ctce: null, b1: null, b2: null, c1: "c1-disc-markers" } },
        { id: 'cs-ellipsis', name: "Ellipsis", levels: { ctce: null, b1: null, b2: null, c1: "c1-ellipsis" } },
        { id: 'cs-substitution', name: "Substitution", levels: { ctce: null, b1: null, b2: null, c1: "c1-substitution" } },
      ]},
      { id: 'nominalization-legacy', name: "Nominalization (B1–C1)", examPart: null, examBlock: null, legacyV10: true, subtopics: [
        { id: 'cs-nominal', name: "Nominalization", levels: { ctce: null, b1: null, b2: null, c1: "c1-nominal" } },
      ]},
    ]
  };

  var LEVEL_TO_CANONICAL = Object.create(null);
  var CANONICAL_TO_TOPIC = Object.create(null);
  CONFIG.topics.forEach(function(topic){
    topic.subtopics.forEach(function(sub){
      CANONICAL_TO_TOPIC[sub.id] = { topic: topic, subtopic: sub };
      Object.keys(sub.levels).forEach(function(levelId){
        var lvlSubId = sub.levels[levelId];
        if (lvlSubId){
          LEVEL_TO_CANONICAL[lvlSubId] = {
            canonicalTopicId: topic.id,
            canonicalSubtopicId: sub.id,
            level: levelId,
            displayName: sub.name
          };
        }
      });
    });
  });

  var CANONICAL_SUB_COUNT = 0;
  var BY_LEVEL_COUNT = { ctce: 0, b1: 0, b2: 0, c1: 0 };
  CONFIG.topics.forEach(function(t){
    CANONICAL_SUB_COUNT += t.subtopics.length;
    t.subtopics.forEach(function(s){
      Object.keys(s.levels).forEach(function(lv){
        if (s.levels[lv]) BY_LEVEL_COUNT[lv]++;
      });
    });
  });

  function topicsForLevels(activeLevels){
    var levelSet = {};
    activeLevels.forEach(function(l){ levelSet[l] = true; });
    var out = [];
    CONFIG.topics.forEach(function(topic){
      var visibleSubs = topic.subtopics.filter(function(sub){
        return Object.keys(sub.levels).some(function(lv){
          return levelSet[lv] && sub.levels[lv];
        });
      });
      if (visibleSubs.length){
        out.push({ id: topic.id, name: topic.name, examPart: topic.examPart, examBlock: topic.examBlock, legacyV10: topic.legacyV10, subtopics: visibleSubs });
      }
    });
    return out;
  }

  function activeLevelChips(canonicalSubId, activeLevels){
    var sub = CANONICAL_TO_TOPIC[canonicalSubId];
    if (!sub) return [];
    var chips = [];
    var displayShortById = {};
    CONFIG.levels.forEach(function(l){ displayShortById[l.id] = l.displayShort; });
    activeLevels.forEach(function(lv){
      if (sub.subtopic.levels[lv]) chips.push(displayShortById[lv]);
    });
    return chips;
  }

  function levelSubtopicIdsFor(canonicalSubId, activeLevels){
    var sub = CANONICAL_TO_TOPIC[canonicalSubId];
    if (!sub) return [];
    var ids = [];
    activeLevels.forEach(function(lv){
      var id = sub.subtopic.levels[lv];
      if (id) ids.push(id);
    });
    return ids;
  }

  var SUBTOPIC_MODES = {};
  ['err-aux','err-prep','err-art','err-pron','err-int','err-para'].forEach(function(k){
    SUBTOPIC_MODES[k] = ['typein'];
  });
  function modesForSubtopic(levelSubId){
    return SUBTOPIC_MODES[levelSubId] || ['mcq','typein'];
  }

  window.LEARN_SUBTOPIC_MODES = SUBTOPIC_MODES;
  window.learnModesForSubtopic = modesForSubtopic;
  window.LEARN_TOPICS_CONFIG = CONFIG;
  window.LEARN_LEVEL_TO_CANONICAL = LEVEL_TO_CANONICAL;
  window.LEARN_CANONICAL_TO_TOPIC = CANONICAL_TO_TOPIC;
  window.LEARN_TAXONOMY_HELPERS = {
    topicsForLevels: topicsForLevels,
    activeLevelChips: activeLevelChips,
    levelSubtopicIdsFor: levelSubtopicIdsFor
  };
  window.LEARN_TAXONOMY_COUNTS = {
    canonicalTopics: CONFIG.topics.length,
    canonicalSubtopics: CANONICAL_SUB_COUNT,
    byLevel: BY_LEVEL_COUNT,
    totalLevelSubtopics: BY_LEVEL_COUNT.ctce + BY_LEVEL_COUNT.b1 + BY_LEVEL_COUNT.b2 + BY_LEVEL_COUNT.c1
  };
})();